import React from 'react';
import { type LucideProps } from 'lucide-react';

import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Baby,
  BadgeEuro,
  Bath,
  BedDouble,
  BedSingle,
  BookMarked,
  Building2,
  CalendarDays,
  CalendarSearch,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Clock,
  ConciergeBell,
  Dog,
  DoorOpen,
  Eye,
  House,
  LayoutTemplate,
  Loader2,
  LogIn,
  LogOut,
  Map,
  Menu,
  Merge,
  Minus,
  Moon,
  Mountain,
  Pencil,
  Phone,
  Plus,
  Receipt,
  RotateCcw,
  ScrollText,
  Search,
  ShieldCheck,
  ShieldX,
  ShowerHead,
  Sofa,
  SplitSquareHorizontal,
  Square,
  Sun,
  Table2,
  ThumbsUp,
  Toilet,
  Trash2,
  Tv,
  User,
  Users,
  Utensils,
  X,
  type LucideIcon,
} from 'lucide-react';

import { BookingStatus } from '@trinserhof/types';

export type Icon = LucideIcon;

export const ICONS = {
  accountingCategory: BookMarked,
  add: Plus,
  adult: User,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  auditLog: ScrollText,
  balcony: Sun,
  bath: Bath,
  bed: BedDouble,
  bedKing: BedDouble,
  bedQueen: BedDouble,
  bedSingle: BedSingle,
  booking: BedDouble,
  calendar: CalendarDays,
  calendarSearch: CalendarSearch,
  check: Check,
  checkIn: LogIn,
  checkOut: LogOut,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  child: Baby,
  close: X,
  dashboard: ConciergeBell,
  decrease: Minus,
  delete: Trash2,
  desk: Table2,
  edit: Pencil,
  guest: User,
  home: House,
  invoice: Receipt,
  loading: Loader2,
  map: Map,
  menu: Menu,
  merge: Merge,
  missing: SplitSquareHorizontal,
  mountain: Mountain,
  noAccess: ShieldX,
  pet: Dog,
  phone: Phone,
  price: BadgeEuro,
  product: Archive,
  property: Building2,
  reset: RotateCcw,
  role: ShieldCheck,
  room: DoorOpen,
  roomType: BedDouble,
  search: Search,
  shower: ShowerHead,
  sofa: Sofa,
  sort: ChevronsUpDown,
  space: Square,
  stay: House,
  table: LayoutTemplate,
  tableBooking: Utensils,
  themeDark: Moon,
  themeLight: Sun,
  toilet: Toilet,
  tv: Tv,
  user: User,
  users: Users,
  view: Eye,
  wipeData: Trash2,
} satisfies Record<string, Icon>;

export const BOOKING_STATUS_ICONS: Record<BookingStatus, Icon> = {
  PENDING: Clock,
  CONFIRMED: ThumbsUp,
  CHECKED_IN: Check,
  CHECKED_OUT: Check,
  CANCELLED: X,
};

const icon = (IconComponent: React.ElementType, defaultSize = 'size-4') => {
  return (props: LucideProps) => (
    <IconComponent {...props} className={`${defaultSize} ${props.className || ''}`} />
  );
};

export const RoomIcon = icon(ICONS.room);
export const CheckOutIcon = icon(ICONS.checkOut);
