export type Page =
  | 'calendar'
  | 'migration'
  | 'bookings-table'
  | 'booking-create'
  | 'customers-table'
  | 'products-table'
  | 'accounting-categories-table'
  | 'users-table'
  | 'rooms-table'
  | 'prices'
  | 'tables-table'
  | 'table-reservations-table'
  | 'raw-data'
  | 'audit-log';
