// export { generateItemsForPayment } from './generateItemsForPayment';
export { bookingsAreDifferent } from './bookingsAreDifferent';
export { calculatePrice } from './calculatePrice';
export { dateToString } from './dateToString';
export { formatCurrency } from './formatCurrency';
export { formatDate } from './formatDate';
export { getAmountOfNightsFromDateRange } from './getAmountOfNightsFromDateRange';
export { getNewBooking } from './getNewBooking';
export { getYYYYmmDD } from './getYYYYmmDD';
export { isValidEmailAddress } from './isValidEmailAddress';
export { makeBookingBackwardsCompatible } from './makeBookingBackwardsCompatible';
export { removeTimeFromDate } from './removeTimeFromDate';
export { uuidv4 } from './uuidv4';
